server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      enable_lazy_load_no_trans: true
      event:
        merge:
          entity_copy_observer: allow
  application:
    name: demo-service


keycloak:
  realm: SchoolManagement
  auth-server-url: http://localhost:8080
  client-id: client
  credentials:
    secret: 9MhSyamAwTge0Uo34yUHdjgZzhVsviP6
  principal-attribute: preferred_username

client-jwk-set-uri: "http://localhost:8080/realms/SchoolManagement/protocol/openid-connect/certs"
jwt:
  auth:
    converter:
      resource-id: client
      principal-attribute: preferred_username