server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iamms
    username: iam
    password: "12345678"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      enable_lazy_load_no_trans: true
      event:
        merge:
          entity_copy_observer: allow
  application:
    name: demo-service


keycloak:
  realm: SchoolManagement
  auth-server-url: https://elaoumrani.com:8444
  client-id: client
  credentials:
    secret: y2z8T3huZyBomThwFPAlRUOjoqoiTaJ9
  principal-attribute: preferred_username

client-jwk-set-uri: "https://elaoumrani:8444/realms/SchoolManagement/protocol/openid-connect/certs"
jwt:
  auth:
    converter:
      resource-id: client
      principal-attribute: preferred_username
